import time
#import vlc (for some reason no matter what I do this does not work :( )
sanity = 0
delirium = 0
#p = vlc.MediaPlayer("KOTHyouWIN.mp3")
#functions

def sanityEnding():
  if sanity == 10:
    print("Wow you won the game, you really are Hank Hill!")

def deliriumEnding():
  if delirium == 10:
    print("This will be a really long-drawn out")
    print("Print about drinking propane and realizing that ")
    print(f"You truly are a nerd behind a computer screen named {name}")
    print("Also some quote about free will would be funny here")

def deliriumUp():
  #delirium += 1
  print("You feel you are growing deranged") #make this a function
  print("Delirium:")
  print(delirium)

def sanityUp():
  #(sanity + 1) 
  print("It feels like you're on the right path.") #make this a function
  print("Sanity:")
  print(sanity)


#The game code starts here!
name = input('What is your name?: ')
print(f"Hello {name}")
time.sleep(1)
print("Welcome to the King of the Hill text adventure!")
#p.play()
time.sleep(1)
start = input("Please choose (play) or (exit): ")
time.sleep(1)
if start == 'play': #game start
  print("Starting the game")
  time.sleep(3)
  print('**************************************************************************************')
  print('*                   You hear the voice of an older Texan man.                        *')
  print('*                    "Well old top, its almost closing time"                         *')
  time.sleep(2)
  print('*        You lift your resting eyes, looking at your reflection in the window.       *')
  print('*                       "What the hell?" You mutter to yourself.                     *')
  time.sleep(2)
  print('*As you yawn,the industrial scents of propane and propane accesories fill your lungs.*')
  print('*          You are sitting at an office desk, it seems familar but... different.     *')
  time.sleep(2)
  print('* You become uncomfortable, as just 5 minutes ago you would swear you were at your PC*')
  print('**************************************************************************************')
  time.sleep(2)
  setting = input("Check your desk (desk) or check your wallet (wallet)?: ")
else:
  print("Exiting game...")
  time.sleep(3)
  print("Goodbye!")
  time.sleep(1)
  quit()

if setting == 'desk':
  print('**************************************************************************************')
  print('*                   You look at the items on top of your desk.                       *')
  print('*The most prominent display on your desk is a framed picture of a middle-aged woman  *')
  print('*            and what appears to be a pre-teen boy with a shaved head.               *')
  time.sleep(2)
  print('*            Upon seeing the photograph, thoughts beging flooding your mind          *')
  time.sleep(2)
  print('*"That boy aint right"                                                               *')
  time.sleep(2)
  print('*                                                              "Saved your life dad. *')
  time.sleep(2)
  print("*                                  That's my purse!                                  *")
  time.sleep(2)
  print('*               "Eschuchame?"                                                        *')
  time.sleep(2)
  print('*   Your mind is racing, but you feel like these two must be related to you closely. *')
  #deliriumUp() Should go here but it doesnt work for god knows why
  print('**************************************************************************************')
elif setting == 'wallet':
  print('**************************************************************************************')
  print('*            You reach into your pockets and find a tan Harley Davidson wallet       *')
  print('*                       You find a drivers license that reads:                       *')
  time.sleep(1)
  print('*Name: Hank Rutherford Hill                                                          *')
  time.sleep(1)
  print('*Age:  41                                                                            *')
  time.sleep(1)
  print('*Address: 123 Rainey Street.                                                         *')
  time.sleep(1)
  print('*Arlen,Texas 73104                                                                   *')
  time.sleep(2)
  print('*                 It doesnt feel right, but you know the info is correct...          *')
  time.sleep(1)
  print(f'*              You feel the name {name} becoming more and more foreign to you.      *')
  print('**************************************************************************************')

time.sleep(4)
print('**************************************************************************************')
print('*                   You hear the the voice of the older man again:                   *')
print('*                                "Didnt yall hear me?                                *')
print('*I need to make it to J.Store Cowboys before Candy leaves, HANK, so get out of here!"*')
time.sleep(2)
print('*        "Im sorry sir, I guess I must have dozed off there" escapes your mouth,     *')
print('*                                almost impulsively.                                 *')
time.sleep(2)
print('*                You and the older man exit the front door of the building           *')
time.sleep(2)
print('*"Sorry for rushing ya Hank, but Candy has a habit of leaving when ol Buck Strickland*')
print('*            doesnt show up at exactly 5:15. She says Im the best tipper!"           *')
time.sleep(2)
print('*    BUCK STRICKLAND enter his car and exits the parket lot, obnoxiously peeling out *')
print('**************************************************************************************')
time.sleep(2)
#if delirium == 0:
  #print('*            Somehow, this interaction has increased your respect for BUCK.          *')
  #print('**************************************************************************************')
setting = input("Go home (home) or walk around (walk)?: ")
if setting == 'home':
  time.sleep(4)
  print('**************************************************************************************')
  print('*                     You walk to what you assume to be your truck                   *')
  time.sleep(1)
  print('*              It is the only one left in the small parking lot, after all.          *')
  time.sleep(2)
  print('*     Once inside you feel the godforsaken sensation of Texas heat on seatbelt clip. *')
  time.sleep(2)
  print('*      "God dang it, god dang it!" you exclaim, now with a small burn on your side.  *')
  time.sleep(2)
  print('*      Your eyes jot around and you notice a stray bottle of water on the floorboard *')
  print('*                       You open the cap and douse your burn in it.                  *')
  print('*                                    TSSSSSssss                                      *')
  time.sleep(2)
  print('*                       "Got-dang seatbelt" you say to yourself.                     *')
  print('**************************************************************************************')
  time.sleep(2)
  print('**************************************************************************************')
  print('*              After taking care of your burn, you begin to drive home.              *')             
  print('**************************************************************************************')
time.sleep(2)
if setting == 'walk':
  time.sleep(4)
  print('**************************************************************************************')
  print('*                       You walk around the back of the store.                       *')
  print('*           You notice a lockup of propane tanks, and next to it a stray tank.       *')
  time.sleep(2)
  print('*                       "Oh my god, a stray tank!" you exclaim.                      *')
  print('* "Gibblet heads. I know its Friday, but that doesnt mean safety takes a back seat." *')
  time.sleep(2)
  print(f'*             {name}... your thoughts begin to drift for a split second.            *')
  print('*                  Your free will has returned to you for a moment.                  *')
  print('**************************************************************************************')
  setting = input("Do you leave the tank where it is (freedom) or put it back (fate)?: ")
  if setting == 'freedom':
    print('**************************************************************************************')
    print('*     You excercise your free-will and choose to not put back the propane tank.      *')
    print('*                          Your mind begins to drift,                                *')
    time.sleep(2)
    print(f'*               "{name}... {name}... why does that sound so familiar?"              *')
    print('**************************************************************************************')
    #deliriumUp() here
  if setting == 'fate':
    print('**************************************************************************************')
    print('*               You follow the path that feels the most... right to you.             *')
    print('*         After putting away the tank and locking the cage, you stand in place,      *')
    print('*                  admiring the all-American beauty of propane tanks.                *')
    time.sleep(2)
    print(f'*                        "Its just so got-dang beautiful."                          *')
    print('**************************************************************************************')
    #sanityUp() here
  time.sleep(3)
  print('**************************************************************************************')
  print('*                  With the propane tank situation taken care of,                    *')             
  print('*                        you figure its time to call it a day                        *')
  print('**************************************************************************************')
  time.sleep(2)
  print('**************************************************************************************')
  print('*                   You get into your truck and start to drive home.                 *')             
  print('**************************************************************************************')
  time.sleep(2)
print("You beat Level 1: A Surprise at Strickland")
#p.play()
time.sleep(2)
print("Here are your stats")
time.sleep(2)
print(f'Delirium: {delirium}')
print(f'Sanity: {sanity}')
time.sleep(2)
setting = input("Enter (continue) to move on!: ")
if setting == 'continue':
  print('*                                Loading level 2...                                  *')
  time.sleep(4)
  print('**************************************************************************************')
  print('*                          You turn your truck into an alley.                        *')
  time.sleep(2)
  print('*                 Youre not entirely sure why, but for some reason you               *')
  print('*                  are able to tell that this must be the way home...                *')
  print('**************************************************************************************')
  time.sleep(2)
  print('**************************************************************************************')
  print('*                          You turn your truck into an alley.                        *')
  time.sleep(2)
  print('*                 Youre not entirely sure why, but for some reason you               *')
  print('*                  are able to tell that this must be the way home...                *')
  print('**************************************************************************************')
  time.sleep(2)
  print('**************************************************************************************')
  print('*As you drive down the alley,you notice 3 men behind what you assume to be your house*')
  time.sleep(2)
  print('*     As you drive by, the men wave, beers in hand and collectively say "Hey Hank!"  *')
  print('*                  are able to tell that this must be the way home...                *')
  print('**************************************************************************************')