import time

#STATS and VARS
grit = 0
luck = 0
inventory = []
oafHealth = 2
gold = 0

carriage = 'false'

#This is where the FUNCTIONS would go... if I had any!
def gameOver():
  print('Your quest has come to an end.')
  time.sleep(2)
  print('The Scourge continues to torment the people of Thesuin.')
  time.sleep(2)
  print(f'Your final stats were: Grit: {grit} Luck: {luck} Gold: {gold}')
  time.sleep(2)
  print('Thank you for playing, see you soon!')
  time.sleep(2)
  quit()
#GAME
print("******************************************************************************************************")
print("                                                                                                      ")
print("                                         Issac's Quest Day 1                                          ")
print("                                A Sapphire and Iron text-adventure:                                   ")
print("                                                                                                      ")
time.sleep(1)
print("                                    Programmed and created by:                                        ")
print("                                    aerospace_dev(Micah Golden)                                       ")
print("                                                                                                      ")
print("                                              v.01                                                    ")
print("******************************************************************************************************")
start = input("Please choose (play) or (exit): ")
time.sleep(1)
if start == 'play':
  time.sleep(2)
  print("Welcome to the world of Sapphire and Iron.")
  time.sleep(3)
  print("In this game you will be taking on the role of Issac, a woodcutter's son and an avid adventurer.")
  print("The world is vast, vaster than may be evident at first, and not all paths are the same!")
  time.sleep(2)
  print("Have fun!")
  time.sleep(1)
  print("Starting game...")
  time.sleep(1)
else:
  print("Exiting game...")
  time.sleep(3)
  print("Goodbye!")
  time.sleep(1)
  quit()
print("*****************************************************************************************************")
print("                                               Issac...                                              ")
time.sleep(3)
print("                                        Issac... Can you hear me?                                    ")
time.sleep(3)
print("                   Your eyes open to a view of a young woman standing above you.                     ") 
print("               She is wearing a blue cloth dress and a hat with a red cross on it.                   ")
time.sleep(2)
print("             You look down and see that your legs are wrapped in a white linen bandage.              ")
time.sleep(2)
print('          "Issac, thank the Gods you are okay! That was quite a nasty wound you hade there."         ')
time.sleep(2)
print("     After coming to, you realize the nurse is none other than Rebecca, a friend of your father's.   ")
time.sleep(2)
print('  "Well now that youre awake, we can see how badly the monster did you in. Could you try standing?"  ')
time.sleep(3)
print("            You can tell that standing will be a bit of challenge, but may be for the best.          ")
choice = input("Do you attempt to (stand) or (stay) in bed?: ")
if choice == 'stand':
  print("****************************************************************************************************")
  print("                     You get out of bed and make a bold attempt to stand up.                        ")
  print("                                              .                                                     ")
  time.sleep(1)
  print("                                              .                                                     ")
  time.sleep(1)
  print("                                              .                                                     ")
  time.sleep(2)
  print("            Unfortunately, your sheer will fails you and you collapse back into the bed,            ")
  time.sleep(1)
  print("                         making your decision to get up feel meaningless...                         ")
  time.sleep(1)
  grit += 1 #ability point increase
  print("            But fret not! You feel you did your best, meaning your GRIT is now stronger!            ")
  print("****************************************************************************************************")
  time.sleep(2)
else:
  print("        You tell Rebecca that you can't feel your legs one bit and you can't move.                  ")

print("****************************************************************************************************")
print('           "Oh thats no good. Let me see if I have anything that can help with...                   ')
time.sleep(3)
print('           Aye, there you are. This should get your strength back for the time being."              ')
time.sleep(2)
print('            Rebecca pours a blue sludgy substance out of a bottle and onto your legs.               ')
time.sleep(3)
print('                    "Ah, dont fret. Its slime escense. Finest around!"                              ')
time.sleep(2)
print('                     Your legs stop feeling numb. You feel... good as new!                          ')
time.sleep(3)
print('                               "There ya are. All better!"                                          ')
time.sleep(2)
print('                            The nurse hesistates for a moment...                                    ')
time.sleep(3)
print('                  "Issac, I actually have need to tell you a couple of things..."                   ')
time.sleep(3)
print('        "To start... you need to take a bottle of this once a day for the next while."              ')
print('        She hands you a small vial of the SLIME ESCENSE and you place it in your satchel.           ')
print("")
time.sleep(2)
print("SLIME ESCENSE HAS BEEN ADDED TO YOUR INVENTORY")
time.sleep(2)
inventory.append('SLIME ESCENSE')
print(f"Your current Inventory: {inventory}")
time.sleep(3)
print('                                        "Also..."                                                   ')
print('      The expression on her face changes to what can only be described as a grave look of sorrow.   ')
time.sleep(3)
print('               "While your legs may have been a casualty with a cure, it seems as though            ')
print('                          the rest of your group may not have been as lucky."                       ')
time.sleep(3)
print('                             Your crew. The moment comes back to you...                             ')
time.sleep(2)
print('"Please I want to live!"                                                                            ')
time.sleep(1)
print('                                   "On Thesus please save me!"                                      ')
time.sleep(1)
print('                                                            "Issac! You cant leave us here!"        ')
time.sleep(2)
print('           Visions of blood on the cave rocks and a scaly red beast flow through your head.         ')
time.sleep(3)
print('   "I know that this must be hard for you... I want you to know that it is not your fault, dear."   ')
time.sleep(3)
print(' You begin to weep, mourning your lost comrades. The nurse holds your hand and looks you in the eye.')
time.sleep(2)
print('                "Their blood is in the hands of the Scourge. You did all you could."                ')
time.sleep(3)
print('                       You stand up, now feeling determined to make this right.                     ')
time.sleep(2)
print('                   "Issac! Dear! You surely arent thinking of going back there, are you?!"          ')
time.sleep(2)
if grit > 0:
  print('   Despite her concern, you begin to make your way to the door, grabbing your jacket on the way.  ')
else:
  print('          You turn your head, as her concerned tone make you reconsider your determination.       ')
time.sleep(2)
print('      "Issac, I know you want to make it right in your mind, but you still arent ready quite yet."  ')
time.sleep(2)
print('"If you are really so sure you want to go back there, at least take a day to get back on your feet."')
time.sleep(2)
print('        "Before he left us, I promised your father that I would mend your wounds when need be.      ')
print('                  That means keeping the healing process all the way until the end."                ')
time.sleep(2)
print('                                Her pleading resonates with you.                                    ')
print('              You agree to spend the day in town, but make no promises as to tomorrow.              ')
time.sleep(2)
print('            "Ill take my chances on tomorrow, but today is the most important." she says            ')
time.sleep(2)
print('  "If you really want to get your spirit back, I think training with Osirus may be a wise decision" ')
time.sleep(2)
print('      Osirus, he was the man who taught your father how to swing an axe, surely he could help you.  ')
time.sleep(2)
print('                                  You begin to walk out the door.                                   ')
time.sleep(2)
print('                               "Goodbye, Issac. Please do be safe."                                 ')
time.sleep(2)
print('                            You are now outside in the center of town.                              ')
print('            Thesuin is an averaged-sized city. Named after Thesius, the God of the east.            ')
print('                 When you were young you used to visit the city with your father,                   ') 
print('                          who would sell his lumber to the carpenters.                              ')
print("****************************************************************************************************")
choice = input("The city is yours! Do you visit (Osirus) or (loft) around?: ")
if choice == 'Osirus':
  print('You decide that it is best to heed the advice given to you by Rebecca and visit Osirus.')
  time.sleep(2)
  print("****************************************************************************************************")
  print("        Osirus' home is on the outskirts of the city, two blocks north of the Apothocary's.         ")
  time.sleep(2)
  print("  As you walk towards the house, you notice that shops on this strip of red brick road are bustling ")
  time.sleep(2)
  print("       You figure it to be about mid-noon and are thankful that you have more time than expected.   ")
  if grit > 0:
    print("     While you may be determined to face the Scourge, you still recognize it to be a challenge.   ")
  print('                Fightning a beast so dreaded by Thesuin that it has been simply dubbed             ') 
  print('                           "The Scourge" predictably being no easy feat.                            ')
  time.sleep(2)
  print('                     "Hey, you! Come here!" a shrill male voice calls out to you.                   ')
  time.sleep(2)
  print("           You look at the man. He appears to be of middle-age, balding, and mustached.             ")
  print("       He dons a blue and grey striped suit that you recognize as a member of the carnival.         ")
  time.sleep(2)
  print('  "Come on, boy. I have a game I want you to try. Beat it and you can win an extraordinary prize!"  ')
  time.sleep(2)
  print('You pause for a moment to think... On one hand, you want to go, on the other, prizes are exciting...')
  time.sleep(2)
  choice = input("Play the (game) or walk (away)?: ")
  if choice == 'game':
    print("**************************************************************************************************")
    time.sleep(2)
    print('                       You tell the man that you would be happy to play.                          ')
    time.sleep(2)
    print('                  "Excellent choice my good sir. Let me explain the game to you."                 ')
    time.sleep(2)
    print('                   "You may have heard of this one, its called Galleyball"                        ')
    time.sleep(2)
    print('       "I am gonna hand you this ball, all you need to do is throw it into one of the baskets.   ') 
    print('                                      If it sticks, you win!"                                     ')
    time.sleep(2)
    print('You look behind the man and see three baskets behind him, however one of them is covered by a tarp')
    time.sleep(2)
    print('  "Now, you can pick any of these baskets you see right here, but do not choose the covered one." ')
    time.sleep(2)
    print('            You ask the man why, and he explains that every winning basket gets retired.          ')
    time.sleep(2)
    print('           "Okay", you figure. Makes about as much sense as anything else this guy has said.      ')
    time.sleep(2)
    print('                        The man steps out of the way and shouts "BEGIN!"                          ')
    choice = input("Do you pick the (first) or (second) basket?: ")
    if choice == 'first':
      print("                          You toss the ball into the first basket...                            ")
      time.sleep(2)
      print("                          It bounces inside of the basket and...                                ")
      time.sleep(2)
      print("                            unfortunately it bounces back out.                                  ")
    if choice == 'second':
      print("                          You toss the ball into the first basket...                            ")
      time.sleep(2)
      print("                           It bounces inside of the basket and...                               ")
      time.sleep(2)
      print("                          It sticks! The ball stays in the basket.                              ")
      time.sleep(2)
      print('                      "And we have a big fat WINNER ladies and gents!"                          ')
      time.sleep(2)
      print('                   You cant believe it. You never win these kinds of games!                     ')
      time.sleep(2)
      print('                             "Oh, well..." the man whispers.                                    ')
      time.sleep(2)
      print('                      "I didnt actually expect you to win this... Mmm..."                       ')
      time.sleep(2)
      print('                  "Well, you didnt pay me first, so it doesnt count! Good day, vagrant."        ')
      time.sleep(2)
      print('                      The man walks to the back of his booth. You feel cheated...               ')
      time.sleep(2)
      luck += 1
      print('                but you also feel LUCKY for winning. Your LUCK has gone up a little!            ')
      time.sleep(2)
    if choice == 'third':
      print("   You toss the ball into the third basket, feeling like this is the trick to winning         ")
      time.sleep(2)
      print("                          It bounces inside of the basket and...                              ")
      time.sleep(2)
      print("                            unfortunately it bounces back out.                                ")
      time.sleep(2)
      print('              "You IDIOT! I told you not to throw it in there, but you did anyways!"          ')
      time.sleep(2)
      print('                 The man storms to the back of his booth, out of your view.                   ')
      time.sleep(2)
      print('         You feel disappointed as your smart-alec attempt to beat the game failed.            ')
      time.sleep(2)
  else:
    print('  You decide that con-men in the street are not worth your time, even if you enjoy a good game.   ')
  time.sleep(2)  
  print("With the distracting allure of a carnival game taken care of, you continue your trek to Osirus'home ")
  time.sleep(2)
else:
  print("***************************************************************************************************")
  time.sleep(2)
  print('               You decide to waste time, lofting around outside of the nurses office,              ')
  print('              somehow making your way to the market festival a couple of blocks away.              ')
  time.sleep(2)
  print('                     "Hey, you! Come here!" a shrill male voice calls out to you.                   ')
  time.sleep(2)
  print("           You look at the man. He appears to be of middle-age, balding, and mustached.             ")
  print("       He dons a blue and grey striped suit that you recognize as a member of the carnival.         ")
  time.sleep(2)
  print('  "Come on, boy. I have a game I want you to try. Beat it and you can win an extraordinary prize!"  ')
  time.sleep(2)
  print('You pause for a moment to think... On one hand, you want to go, on the other, prizes are exciting...')
  time.sleep(2)
  choice = input("Play the (game) or walk (away)?: ")
  if choice == 'game':
    print("**************************************************************************************************")
    time.sleep(2)
    print('                       You tell the man that you would be happy to play.                          ')
    time.sleep(2)
    print('                  "Excellent choice my good sir. Let me explain the game to you."                 ')
    time.sleep(2)
    print('                   "You may have heard of this one, its called Galleyball"                        ')
    time.sleep(2)
    print('       "I am gonna hand you this ball, all you need to do is throw it into one of the baskets.   ') 
    print('                                      If it sticks, you win!"                                     ')
    time.sleep(2)
    print('You look behind the man and see three baskets behind him, however one of them is covered by a tarp')
    time.sleep(2)
    print('  "Now, you can pick any of these baskets you see right here, but do not choose the covered one." ')
    time.sleep(2)
    print('            You ask the man why, and he explains that every winning basket gets retired.          ')
    time.sleep(2)
    print('           "Okay", you figure. Makes about as much sense as anything else this guy has said.      ')
    time.sleep(2)
    print('                        The man steps out of the way and shouts "BEGIN!"                          ')
    choice = input("Do you pick the (first) or (second) basket?: ")
    if choice == 'first':
      print("                          You toss the ball into the first basket...                            ")
      time.sleep(2)
      print("                          It bounces inside of the basket and...                                ")
      time.sleep(2)
      print("                            unfortunately it bounces back out.                                  ")
    if choice == 'second':
      print("                          You toss the ball into the first basket...                            ")
      time.sleep(2)
      print("                           It bounces inside of the basket and...                               ")
      time.sleep(2)
      print("                          It sticks! The ball stays in the basket.                              ")
      time.sleep(2)
      print('                      "And we have a big fat WINNER ladies and gents!"                          ')
      time.sleep(2)
      print('                   You cant believe it. You never win these kinds of games!                     ')
      time.sleep(2)
      print('                             "Oh, well..." the man whispers.                                    ')
      time.sleep(2)
      print('                      "I didnt actually expect you to win this... Mmm..."                       ')
      time.sleep(2)
      print('                  "Well, you didnt pay me first, so it doesnt count! Good day, vagrant."        ')
      time.sleep(2)
      print('                      The man walks to the back of his booth. You feel cheated...               ')
      time.sleep(2)
      luck += 1
      print('                but you also feel LUCKY for winning. Your LUCK has gone up a little!            ')
      time.sleep(2)
    if choice == 'third':
      print("   You toss the ball into the third basket, feeling like this is the trick to winning           ")
      time.sleep(2)
      print("                          It bounces inside of the basket and...                                ")
      time.sleep(2)
      print("                            unfortunately it bounces back out.                                  ")
      time.sleep(2)
      print('              "You IDIOT! I told you not to throw it in there, but you did anyways!"            ')
      time.sleep(2)
      print('                 The man storms to the back of his booth, out of your view.                     ')
      time.sleep(2)
      print('         You feel disappointed as your smart-alec attempt to beat the game failed.              ')
      time.sleep(2)
  else:
    print('  You decide that con-men in the street are not worth your time, even if you enjoy a good game.   ')
  time.sleep(2)  
  print("With the distracting allure of a carnival game taken care of, you decide it's time to head to Osirus'home ")
  time.sleep(2)
print('               You continue to make your way down the path and hit a fork in the road.                ')
time.sleep(2)
print('               It seems to be a tired cliche at this point in your adventuring career,                ')
time.sleep(2)
print('                        but you still must choose a direction all the same.                           ')
time.sleep(2)
print("                                There's a signpost in the middle,                                     ")
print('               the left arrow reads "Northern Wall" and the right reads "Eastern Wall".               ')
time.sleep(2)
choice = input("Do you head (left) or go to the (right)?: ")
time.sleep(2)
if choice == 'left':
#region LEFT
  print("**************************************************************************************************")
  print("  You make your way left, towards the Northern Wall, as you remembered Osirus' house being north. ")
  time.sleep(2)
  print("                As you continue down the path, the brick road begins to turn to dirt.             ")
  time.sleep(2)
  print('       You look around and notice that this area is full of sketchy bars and immoral pleasures.   ')
  time.sleep(2)
  print('          "Hey, whats a kid like you doing here in the Under Belly?" a gruff man espouses.        ')
  time.sleep(2)
  print('                    You wave him off, telling him to go join the Scourge for tea.                 ')
  time.sleep(2)
  print('                        "Ah, a bit insolant are ye? Well in that case..."                         ')
  print('       The man charges at you. While he bears only his fists, he has about 50 pounds on you.      ')
  time.sleep(2)
  print('               "If ya want to talk to me like a man, then you also fight as a man!"               ')
  print('                   It would take some LUCK for you to be able to defeat the man.                  ')
  choice = input("Do you (fight) or attempt to (run)?: ")
  if choice == 'fight':
    print('             You decide that you can take this fat oaf, even if he is larger than you.          ')
    time.sleep(2)
    print("**************************************************************************************************")
    print('COMBAT TUTORIAL READ CAREFULLY          ')
    time.sleep(2)
    print('In combat you have two commands:      ')
    time.sleep(2)
    print('(attack) (guard)')
    time.sleep(2)
    print('Pay attention to the queues to know when to (attack) or (guard)')
    time.sleep(2)
    print('Be wise with your timing!')
    time.sleep(2)
    print(f'Right now, your satchel contains {inventory}, which is useless in this fight.')
    time.sleep(2)
    print(f'Your stats are: LUCK: {luck} GRIT: {grit}')
    time.sleep(6)
    print('                   The man is racing towards you with his fist clenched.                          ')
    choice = input("It's your turn (attack) or (guard)?: ")
    if choice == 'attack' and luck > 0:
      print('   As the man is about to swing, you press your luck and try to swing before he can reach you.  ')
      time.sleep(2)
      print('                           While this was a bold choice, it pays off!                           ')
      time.sleep(2)
      print('                          Your fist crashes into the side of his face.                          ')
      time.sleep(2)
      oafHealth -= 1
      print('            The oaf is taken aback, just standing in place trying to catch his breath.          ')
    if choice == 'guard':
      print('                  The man lunges towards you and his fist makes contact with you.               ')
      time.sleep(2)
      print('  Fortuantely, you had the foresight to block this attack, leaving you virtually unharmed.      ')
      time.sleep(2)
    if choice == 'attack' and luck < 1:
      print('       Despite feeling weak, despite not feeling lucky, and despite your better judgement...    ')
      time.sleep(2)
      print('           You attempt to swing at the 300 pound man hurling his fist directly at you.          ')
      time.sleep(2)
      print('                         This predictably goes as you would expect.                             ')
      print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
      time.sleep(2)
      print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
      time.sleep(2)
      gameOver()
    choice = input("It's your turn (attack) or (guard)?: ")
    if choice == 'attack' and oafHealth < 2:
      print('                 You take advantage of the situation and go in for a final blow.              ')
      time.sleep(1)
      print('                                       C                                                      ')
      time.sleep(1)
      print('                                       R                                                      ')
      time.sleep(1)
      print('                                       A                                                      ')
      time.sleep(1)
      print('                                       S                                                      ')
      time.sleep(1)
      print('                                       H                                                      ')
      time.sleep(2)
      print('                    The man is knocked out cold on the ground.                                ')
      time.sleep(2)
      print('             He even dropped 5 gold, which you hastily pocket for yourself.                   ')
      gold += 5
      time.sleep(2)
      print('         All around you citzens gawk, appearing surprised at what just happened.              ')
      time.sleep(2)
      print('   You think you even hear a few claps. This man must have been the bane of Under Belly!      ')
      time.sleep(2)
      print('               Surely this is the worst youd find here so early in the day!                   ')
      time.sleep(2)
      print("     You continue to head towards Osirus' house, now feeling your GRIT has improved.          ")
      grit += 1
      time.sleep(2)
    if choice == 'attack' and oafHealth > 1:
      print('                 You take advantage of the situation and go in for an attack!                   ')
      time.sleep(2)
      print('                          Your fist crashes into the side of his face.                          ')
      time.sleep(2)
      oafHealth -= 1
      print('                 The oaf is taken aback, but quickly gets into attack position.                 ')
      time.sleep(2)
      print('               "Aye, you think youre pretty clever, eh? Well that changes now!"                 ')
      choice = input("It's your turn (attack) or (guard)?: ")
      if choice == 'attack':
        print('       Despite feeling weak, despite not feeling lucky, and despite your better judgement...    ')
        time.sleep(2)
        print('           You attempt to swing at the 300 pound man hurling his fist directly at you.          ')
        time.sleep(2)
        print('                         This predictably goes as you would expect.                             ')
        print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
        time.sleep(2)
        print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
        time.sleep(2)
        gameOver()
      if choice == 'guard':
        print('                  The man lunges towards you and his fist makes contact with you.               ')
        time.sleep(2)
        print('  Fortuantely, you had the foresight to block this attack, leaving you virtually unharmed.      ')
        time.sleep(2)
        print('          The man is catching his breath, as he put all his energy into that attack.       ')
        choice = input("It's your turn (attack) or (guard)?: ")
        if choice == 'attack':
          print('                 You take advantage of the situation and go in for a final blow.              ')
          time.sleep(2)
          print('                                       C                                                      ')
          time.sleep(1)
          print('                                       R                                                      ')
          time.sleep(1)
          print('                                       A                                                      ')
          time.sleep(1)
          print('                                       S                                                      ')
          time.sleep(1)
          print('                                       H                                                      ')
          time.sleep(2)
          print('                    The man is knocked out cold on the ground.                                ')
          time.sleep(2)
          print('             He even dropped 5 gold, which you hastily pocket for yourself.                   ')
          gold += 5
          time.sleep(2)
          print('         All around you citzens gawk, appearing surprised at what just happened.              ')
          time.sleep(2)
          print('   You think you even hear a few claps. This man must have been the bane of Under Belly!      ')
          time.sleep(2)
          print('               Surely this is the worst youd find here so early in the day!                   ')
          time.sleep(2)
          print("     You continue to head towards Osirus' house, now feeling your GRIT has improved.          ")
          grit += 1
          time.sleep(2)
        if choice == 'guard':
          print('                   Feeling overly cautious, you guard *just in case*.                           ')
          time.sleep(2)
          print('                The man catches his breath and is ready to strike again.                        ')
          time.sleep(2)
          print('          Now seeing past your predictable "guard","guard" pattern, you are vulnerable!         ')
          time.sleep(2)
          print('           The man fakes you out, and punches you with all his might in your face.              ')
          time.sleep(2)
          print('                         This predictably goes as you would expect.                             ')
          print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
          time.sleep(2)
          print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
          time.sleep(2)
          gameOver()
    if choice == 'guard':
      print('                   Feeling overly cautious, you guard *just in case*.                           ')
      time.sleep(2)
      print('                The man catches his breath and is ready to strike again.                        ')
      time.sleep(2)
      print('          Now seeing past your predictable "guard","guard" pattern, you are vulnerable!         ')
      time.sleep(2)
      print('           The man fakes you out, and punches you with all his might in your face.              ')
      time.sleep(2)
      print('                         This predictably goes as you would expect.                             ')
      print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
      time.sleep(2)
      print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
      time.sleep(2)
      gameOver()
  if choice == 'run':
    print('         You decide that wasting your time with a petty streer ruffian just isnt worth it.        ')
    time.sleep(2)
    print('            "Hey where are you going, punk?!" the oaf screams as you run passed him.              ')
    time.sleep(2)
    if luck > 0:
      print('   You feel cocky from your earlier victory, so you insult him one last time for good measure.  ')
      time.sleep(2)
    print("                  You escape from the oaf and continue your way to Osirus' house.                 ")
#endregion
else:
  time.sleep(2)
  print("****************************************************************************************************")
  print('                        You decide to head right, towards the eastern wall.                         ')
  time.sleep(2)
  print('                The red brick path suddenly changes into a softer, grassy path.                     ')
  time.sleep(2)
  print('                        Before you know it, you are at the eastern wall!                            ')
  time.sleep(2)
  print('           "Welcome to the Trade District, son!" an older man with a black beard says to you.       ')
  time.sleep(2)
  print('            He appears to be a blacksmith of some sort, as he is currently smelting iron.           ')
  time.sleep(2)
  print('             "Aye, I recognize that look any day! First time in the Trade District, boy?"           ')
  time.sleep(2)
  print("         You tell him yes, and explain that you are trying to get to Osirus' for training.          ")
  time.sleep(2)
  print('      "Well, sure am glad ya didnt make it towards the North! May be a little longer this way..."   ')
  time.sleep(2)
  print('           "but some ass has been harassing any passer by that looks at him the wrong way!"         ')
  time.sleep(2)
  print('                      The man holds out his calloused hand for a handshake.                         ')
  time.sleep(2)
  print('                  "By the way, names Ramsay. Im the head blacksmith around these parts."            ')
  time.sleep(2)
  print('                You shake his hand and introduce yourself as Issac. Son of a woodcutter.            ')
  time.sleep(2)
  print('                     "Aye, I know the one! Used to come around here quite often."                   ')
  time.sleep(2)
  print('                   "Was a good man. The new lumberjack charges double what he did!"                 ')
  time.sleep(2)
  print("           You and the man chuckle together, remembering your fathers generous spirit.              ")
  time.sleep(2)
  print('       "Well son, any friend of his is a friend of mine. If you need help getting to Osirus..."     ')
  time.sleep(2)
  print('                  The man points to a carriage with a grey horse attached to it.                    ')
  time.sleep(2)
  print('      "That carriage leaves for the Northern Wall in an hours time. Ill pay your fare, if..."       ')
  time.sleep(2)
  print('    "Ya help me collect a debt Im owed. Simple really, just dont have the time!" the man laughs.    ')
  time.sleep(2)
  print('           You agree to help the man secure his debt, but you are not thrilled about it.            ')
  time.sleep(2)
  print('                  "Great! All you need to do is head to that house over there."                     ')
  time.sleep(2)
  print('          Ramsay fingers a house that appears to be somewhat extravagant for the area.              ')
  print(' It is a hue of violet and is three stories tall. It has three large round windows and an iron door.')
  print('      The warm reflection of the sun on the iron door hurts your eyes for looking at it too long.   ')
  time.sleep(2)
  print('            "Now, Im pretty sure you can guess what those uptight asses owe me for..."              ')
  print('        "Tell them if they dont pay up, Ill smelt the damn door in the middle of the night!."       ')
  time.sleep(2)
  print('                                  "Oh, and you might need this."                                    ')
  time.sleep(2)
  print('              Ramsay hands you a money form for the deliquent account holders to fill out.          ')
  print("'MONEY FORM' has been added to your inventory!")
  inventory.append('MONEY FORM')
  time.sleep(2)
  print(f' Your current inventory: {inventory}')
  time.sleep(2)
  print("****************************************************************************************************")
  print('    You begin to make your way towards the horrid-yet-extravagant house with a gleam in your eye.   ')
  print("                  It's a simple debt collection, it can't be too hard... right?                     ")
  time.sleep(2)
  print('      As you walk up the steps to their iron door, the sun seems to grow brighter and brighter.     ')
  print("    Maybe it wouldn't be such a bad thing if this door did get smelted away, you begin thinking.    ")
  time.sleep(2)
  print("          You knock on the metal monstrosity and feel your hands begin to burn with each knock.     ")
  time.sleep(4)
  print("                   You wait a moment, and the door begins to loudly clang open.                     ")
  time.sleep(2)
  print("                   Out steps a short portly fellow wearing around 41 wearing a top hat.             ")
  print("        He twirls his mustache and gives you a dead-eyed look, as if he know why you are here.      ")
  time.sleep(2)
  print('                "Can I help you, sir?" the man says in a high-pitched yet monotone fashion.         ')
  time.sleep(2)
  print('        Trying to hold in your laughter, you tell him that you are here on behalf of Ramsay.        ')
  time.sleep(2)
  print('  He gasps, "Why would I pay that man! Do you see this thing? The hinges were not oiled properly!"  ')
  time.sleep(2)
  print('           "No, no, that will not do until he comes here and fixes this terrible clanging!"         ')
  time.sleep(2)
  print('           "Now, if you would leave me be, I have some guests coming in about thirty minutes!"      ')
  time.sleep(2)
  choice = input("Do you (call) his bluff or (threaten) him?: ")
  if choice == 'bluff':
    print('   You remain addamant that he owes money, and tell him that the project has been completed.     ')
    time.sleep(2)
    print('                "I have already told you, sir, this clanging is insufferable!"                   ')
    time.sleep(2)
    print('    The man seems to be confident that this will get him out of paying the bill at this time.    ')
    time.sleep(2)
    print('                     The man stops and appears to think for a moment.                            ')
    time.sleep(2)
    print('                           "You know what kid, tell you what."                                   ') 
    print('  "My back hurts. I havent made my payment for this door yet because I need medicine first."     ')
    time.sleep(2)
    print('        "If you can help me with that, I would be more than happy to sign that form."            ')
    time.sleep(2)
    print('You think for a moment and then remember that the nurse gave you a vial of SLIME ESCENSE earlier.')
    time.sleep(2)
    print("                 You're reluctant, but you feel like this may be the only way.                   ")
    time.sleep(2)
    print("          You tell the man that you will give him some medicine after he signs the form.         ")
    time.sleep(2)
    print('         "Before?! Why the hell would I agree to do that? Do you take me for a fool?"            ')
    print()
  if choice == 'threaten' and grit > 0:
    print("You raise your fist and make it known that if the form isn't signed with ink, it will with blood.")
    time.sleep(2)
    print('  "Thesus, no! Okay you swine, I will sign this stupid form. Hand it to me and leave me alone!"  ')
    time.sleep(2)
    print(' You hand the form over to the man, and he quickly signs it. ')
    time.sleep(2)
    print('     "You got what you want, now leave before I call the guard!" the man hurries back inside.    ')
    time.sleep(2)
    inventory.pop('MONEY FORM')
    inventory.append('MONEY FORM SIGNED')
    print('The MONEY FORM has been replaced with MONEY FORM SIGNED')
    time.sleep(2)
    print(f'Your current inventory: {inventory}')
    time.sleep(4)
  if choice == 'threaten' and grit < 1:
    print("     You tell the man that you'll crash his party if he doesn't sign the form immediately.       ")
    time.sleep(2)
    print('                "Go ahead, just make sure to bring some soup." the man jests.                    ')
    time.sleep(2)
    print("                You don't seem to have enough GRIT to threaten the man properly.                 ")
    
  













print('                            A couple of hours pass as you travel down the path.                       ')
time.sleep(2)
print("                           Before you know it, you've reached the Northern Wall!                      ")
time.sleep(2)
if carriage == 'true':
  print("                          You step out of the carriage and thank the man.                           ")
  print('                   "Dont mention it, kid. Tell the old man Ramsay sends his regards!                ')
  time.sleep(2)
print("                                You take in the sight of the house.                                   ")
time.sleep(2)
print("                       It's a simple hut, really, but it's also majestic.                             ")
time.sleep(2)
print("            Throughout the year, the Northern Wall area is continuously covered in snow,              ")
print("                   save for this short, two-week season known as 'Northern Jubilee'                   ")
time.sleep(2)
print("    Because of the large amount of water left over from the snow melting, flowers grow more vibrant,  ")
print("        the oak trees grow more than 12 feet taller, and the grass is a dark, healthy green.          ")
time.sleep(1)
print("         All this only compliments Osirus' humble hut, which is made of a vibrant yellow brick.       ")
time.sleep(2)
print('                   As you look in awe, the front door of the house is opened.                         ')
time.sleep(2)
print('                               "Ah, Issac. After all these years..."                                  ')
print("  The old man stands atop the hill his house is built upon, staff in hand, and white beard flowing.   ")
time.sleep(2)
print('                     "Your father told me that you would come to me after he passed..."               ')
time.sleep(2)
print('                              The man begins to laugh hysterically.                                   ')
time.sleep(2)
print('                         "I just wish I had put the tea on the pot first!"                            ')
time.sleep(4)
print("                                              .                                                     ")
time.sleep(1)
print("                                              .                                                     ")
time.sleep(1)
print("                                              .                                                     ")
time.sleep(2)
print(' CONGRATULATIONS! ')
time.sleep(2)
print(" You have reached the end of day 1 of Issac's Quest! ")
time.sleep(2)
print(" Issac finally made it to Osirus, and will be ready to train next time. ")
time.sleep(2)
print(f'Your final stats were: Grit: {grit} Luck: {luck} Gold: {gold}')
time.sleep(2)
print('Thank you for playing, see you soon!')
time.sleep(2)
quit()