import time

#STATS and VARS
grit = 0
luck = 1
inventory = []
oafHealth = 2
gold = 0

#This is where the FUNCTIONS would go... if I had any!
def gameOver():
  print('Your quest has come to an end.')
  time.sleep(2)
  print('The Scourge continues to torment the people of Thesuin.')
  time.sleep(2)
  print(f'Your final stats were: Grit: {grit} Luck: {luck} Gold: {gold}')
  time.sleep(2)
  print('Thank you for playing, see you soon!')
  time.sleep(2)
  quit()

choice = input("Do you (fight) or attempt to (run)?: ")
if choice == 'fight':
    print('             You decide that you can take this fat oaf, even if he is larger than you.          ')
    
    print('                   The man is racing towards you with his fist clenched.                          ')
    choice = input("It's your turn (attack) or (guard)?: ")
    if choice == 'attack' and luck > 0:
      print('   As the man is about to swing, you press your luck and try to swing before he can reach you.  ')
      time.sleep(2)
      print('                           While this was a bold choice, it pays off!                           ')
      time.sleep(2)
      print('                          Your fist crashes into the side of his face.                          ')
      time.sleep(2)
      oafHealth -= 1
      print('            The oaf is taken aback, just standing in place trying to catch his breath.          ')
    if choice == 'guard':
      print('                  The man lunges towards you and his fist makes contact with you.               ')
      time.sleep(2)
      print('  Fortuantely, you had the foresight to block this attack, leaving you virtually unharmed.      ')
      time.sleep(2)
    if choice == 'attack' and luck < 1:
      print('       Despite feeling weak, despite not feeling lucky, and despite your better judgement...    ')
      time.sleep(2)
      print('           You attempt to swing at the 300 pound man hurling his fist directly at you.          ')
      time.sleep(2)
      print('                         This predictably goes as you would expect.                             ')
      print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
      time.sleep(2)
      print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
      time.sleep(2)
      gameOver()
    choice = input("It's your turn (attack) or (guard)?: ")
    if choice == 'attack' and oafHealth < 2:
      print('                 You take advantage of the situation and go in for a final blow.              ')
      time.sleep(2)
      print('                                       C                                                      ')
      time.sleep(1)
      print('                                       R                                                      ')
      time.sleep(1)
      print('                                       A                                                      ')
      time.sleep(1)
      print('                                       S                                                      ')
      time.sleep(1)
      print('                                       H                                                      ')
      time.sleep(2)
      print('                    The man is knocked out cold on the ground.                                ')
      time.sleep(2)
      print('             He even dropped 5 gold, which you hastily pocket for yourself.                   ')
      gold += 5
      time.sleep(2)
      print('         All around you citzens gawk, appearing surprised at what just happened.              ')
      time.sleep(2)
      print('   You think you even hear a few claps. This man must have been the bane of Under Belly!      ')
      time.sleep(2)
      print('               Surely this is the worst youd find here so early in the day!                   ')
      time.sleep(2)
      print("     You continue to head towards Osirus' house, now feeling your GRIT has improved.          ")
      grit += 1
      time.sleep(2)
    if choice == 'attack' and oafHealth > 1:
      print('                 You take advantage of the situation and go in for an attack!                   ')
      time.sleep(2)
      print('                          Your fist crashes into the side of his face.                          ')
      time.sleep(2)
      oafHealth -= 1
      print('                 The oaf is taken aback, but quickly gets into attack position.                 ')
      time.sleep(2)
      print('               "Aye, you think youre pretty clever, eh? Well that changes now!"                 ')
      choice = input("It's your turn (attack) or (guard)?: ")
      if choice == 'attack':
        print('       Despite feeling weak, despite not feeling lucky, and despite your better judgement...    ')
        time.sleep(2)
        print('           You attempt to swing at the 300 pound man hurling his fist directly at you.          ')
        time.sleep(2)
        print('                         This predictably goes as you would expect.                             ')
        print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
        time.sleep(2)
        print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
        time.sleep(2)
        gameOver()
      if choice == 'guard':
        print('                  The man lunges towards you and his fist makes contact with you.               ')
        time.sleep(2)
        print('  Fortuantely, you had the foresight to block this attack, leaving you virtually unharmed.      ')
        time.sleep(2)
        choice = input("It's your turn (attack) or (guard)?: ")
        if choice == 'attack':
          print('                 You take advantage of the situation and go in for a final blow.              ')
          time.sleep(2)
          print('                                       C                                                      ')
          time.sleep(1)
          print('                                       R                                                      ')
          time.sleep(1)
          print('                                       A                                                      ')
          time.sleep(1)
          print('                                       S                                                      ')
          time.sleep(1)
          print('                                       H                                                      ')
          time.sleep(2)
          print('                    The man is knocked out cold on the ground.                                ')
          time.sleep(2)
          print('             He even dropped 5 gold, which you hastily pocket for yourself.                   ')
          gold += 5
          time.sleep(2)
          print('         All around you citzens gawk, appearing surprised at what just happened.              ')
          time.sleep(2)
          print('   You think you even hear a few claps. This man must have been the bane of Under Belly!      ')
          time.sleep(2)
          print('               Surely this is the worst youd find here so early in the day!                   ')
          time.sleep(2)
          print("     You continue to head towards Osirus' house, now feeling your GRIT has improved.          ")
          grit += 1
          time.sleep(2)
        if choice == 'guard':
          print('                   Feeling overly cautious, you guard *just in case*.                           ')
          time.sleep(2)
          print('                The man catches his breath and is ready to strike again.                        ')
          time.sleep(2)
          print('          Now seeing past your predictable "guard","guard" pattern, you are vulnerable!         ')
          time.sleep(2)
          print('           The man fakes you out, and punches you with all his might in your face.              ')
          time.sleep(2)
          print('                         This predictably goes as you would expect.                             ')
          print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
          time.sleep(2)
          print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
          time.sleep(2)
          gameOver()
    if choice == 'guard':
      print('                   Feeling overly cautious, you guard *just in case*.                           ')
      time.sleep(2)
      print('                The man catches his breath and is ready to strike again.                        ')
      time.sleep(2)
      print('          Now seeing past your predictable "guard","guard" pattern, you are vulnerable!         ')
      time.sleep(2)
      print('           The man fakes you out, and punches you with all his might in your face.              ')
      time.sleep(2)
      print('                         This predictably goes as you would expect.                             ')
      print('       The man has knocked you out on the ground. Your conciousness begins to fade...           ')
      time.sleep(2)
      print('                   "Maybe next time you wont be so cocky... Stupid kid..."                      ')
      time.sleep(2)
      gameOver()
print('this means that the battle tree worked!')