import time

#STATS and VARS
grit = 0
luck = 1
inventory = []
oafHealth = 2
gold = 0

#This is where the FUNCTIONS would go... if I had any!
def gameOver():
  print('Your quest has come to an end.')
  time.sleep(2)
  print('The Scourge continues to torment the people of Thesuin.')
  time.sleep(2)
  print(f'Your final stats were: Grit: {grit} Luck: {luck} Gold: {gold}')
  time.sleep(2)
  print('Thank you for playing, see you soon!')
  time.sleep(2)
  quit()

  time.sleep(2)
  print("****************************************************************************************************")
  print('                        You decide to head right, towards the eastern wall.                         ')
  time.sleep(2)
  print('                The red brick path suddenly changes into a softer, grassy path.                     ')
  time.sleep(2)
  print('                        Before you know it, you are at the eastern wall!                            ')
  time.sleep(2)
  print('           "Welcome to the Trade District, son!" an older man with a black beard says to you.       ')
  time.sleep(2)
  print('            He appears to be a blacksmith of some sort, as he is currently smelting iron.           ')
  time.sleep(2)
  print('             "Aye, I recognize that look any day! First time in the Trade District, boy?"           ')
  time.sleep(2)
  print("         You tell him yes, and explain that you are trying to get to Osirus' for training.          ")
  time.sleep(2)
  print('      "Well, sure am glad ya didnt make it towards the North! May be a little longer this way..."   ')
  time.sleep(2)
  print('           "but some ass has been harassing any passer by that looks at him the wrong way!"         ')
  time.sleep(2)
  print('                      The man holds out his calloused hand for a handshake.                         ')
  time.sleep(2)
  print('                  "By the way, names Ramsay. Im the head blacksmith around these parts."            ')
  time.sleep(2)
  print('                You shake his hand and introduce yourself as Issac. Son of a woodcutter.            ')
  time.sleep(2)
  print('                     "Aye, I know the one! Used to come around here quite often."                   ')
  time.sleep(2)
  print('                   "Was a good man. The new lumberjack charges double what he did!"                 ')
  time.sleep(2)
  print("           You and the man chuckle together, remembering your fathers generous spirit.              ")
  time.sleep(2)
  print('       "Well son, any friend of his is a friend of mine. If you need help getting to Osirus..."     ')
  time.sleep(2)
  print('                  The man points to a carriage with a grey horse attached to it.                    ')
  time.sleep(2)
  print('      "That carriage leaves for the Northern Wall in an hours time. Ill pay your fare, if..."       ')
  time.sleep(2)
  print('    "Ya help me collect a debt Im owed. Simple really, just dont have the time!" the man laughs.    ')
  time.sleep(2)
  print('           You agree to help the man secure his debt, but you are not thrilled about it.            ')
  time.sleep(2)
  print('                  "Great! All you need to do is head to that house over there."                     ')
  time.sleep(2)
  print('          Ramsay fingers a house that appears to be somewhat extravagant for the area.              ')
  print(' It is a hue of violet and is three stories tall. It has three large round windows and an iron door.')
  print('      The warm reflection of the sun on the iron door hurts your eyes for looking at it too long.   ')
  time.sleep(2)
  print('            "Now, Im pretty sure you can guess what those uptight asses owe me for..."              ')
  print('        "Tell them if they dont pay up, Ill smelt the damn door in the middle of the night!."       ')
  time.sleep(2)
  print('                                  "Oh, and you might need this."                                    ')
  time.sleep(2)
  print('              Ramsay hands you a money form for the deliquent account holders to fill out.          ')
  print("'MONEY FORM' has been added to your inventory!")
  inventory.append('MONEY FORM')
  time.sleep(2)
  print(f' Your current inventory: {inventory}')
  time.sleep(2)
  print("****************************************************************************************************")
  print('    You begin to make your way towards the horrid-yet-extravagant house with a gleam in your eye.   ')
  print("                  It's a simple debt collection, it can't be too hard... right?                     ")
  time.sleep(2)
  print('      As you walk up the steps to their iron door, the sun seems to grow brighter and brighter.     ')
  print("    Maybe it wouldn't be such a bad thing if this door did get smelted away, you begin thinking.    ")
  time.sleep(2)
  print("          You knock on the metal monstrosity and feel your hands begin to burn with each knock.     ")
  time.sleep(4)
  print("                   You wait a moment, and the door begins to loudly clang open.                     ")
  time.sleep(2)
  print("                   Out steps a short portly fellow wearing around 41 wearing a top hat.             ")
  print("        He twirls his mustache and gives you a dead-eyed look, as if he know why you are here.      ")
  time.sleep(2)
  print('                "Can I help you, sir?" the man says in a high-pitched yet monotone fashion.         ')
  time.sleep(2)
  print('        Trying to hold in your laughter, you tell him that you are here on behalf of Ramsay.        ')
  time.sleep(2)
  print('  He gasps, "Why would I pay that man! Do you see this thing? The hinges were not oiled properly!"  ')
  time.sleep(2)
  print('           "No, no, that will not do until he comes here and fixes this terrible clanging!"         ')
  time.sleep(2)
  print('           "Now, if you would leave me be, I have some guests coming in about thirty minutes!"      ')
  time.sleep(2)
  choice = input("Do you (call) his bluff or (threaten) him?: ")
  if choice == 'bluff':
    print('   You remain addamant that he owes money, and tell him that the project has been completed.     ')
    time.sleep(2)
    print('                "I have already told you, sir, this clanging is insufferable!"                   ')
    time.sleep(2)
    print('    The man seems to be confident that this will get him out of paying the bill at this time.    ')
    time.sleep(2)
    print('                     The man stops and appears to think for a moment.                            ')
    time.sleep(2)
    print('                           "You know what kid, tell you what."                                   ') 
    print('  "My back hurts. I havent made my payment for this door yet because I need medicine first."     ')
    time.sleep(2)
    print('        "If you can help me with that, I would be more than happy to sign that form."            ')
    time.sleep(2)
    print('You think for a moment and then remember that the nurse gave you a vial of SLIME ESCENSE earlier.')
    time.sleep(2)
    print("                 You're reluctant, but you feel like this may be the only way.                   ")
    time.sleep(2)
    print("          You tell the man that you will give him some medicine after he signs the form.         ")
    time.sleep(2)
    print('         "Before?! Why the hell would I agree to do that? Do you take me for a fool?"            ')
    time.sleep(2)
    print('     You glare at the man and tell him that you will break his legs too if he doesnt comply.     ')
    time.sleep(2)
    print('                                  "O-okay you thug! Here!"                                       ')
    time.sleep(2)
    inventory.pop('MONEY FORM')
    inventory.append('MONEY FORM SIGNED')
    print('The MONEY FORM has been replaced with MONEY FORM SIGNED')
    time.sleep(2)
    print(f'Your current inventory: {inventory}')
    time.sleep(4)
    print('   You throw some of the SLIME ESCENSE onto the mans hand and tell him to figure it out himself. ')
    time.sleep(2)
    print('                  He applies the SLIME ESCENSE and instantly stands upright.                     ')
    time.sleep(2)
    print('       "Thank you!... Now get the hell out of here!" The man slams the door in your face.        ')
    time.sleep(2)
    print('              Now that you have the MONEY FORM SIGNED, you decide to return to Ramsay.           ')
    time.sleep(2)
  if choice == 'threaten' and grit > 0:
    print("You raise your fist and make it known that if the form isn't signed with ink, it will with blood.")
    time.sleep(2)
    print('  "Thesus, no! Okay you swine, I will sign this stupid form. Hand it to me and leave me alone!"  ')
    time.sleep(2)
    print(' You hand the form over to the man, and he quickly signs it. ')
    time.sleep(2)
    print('     "You got what you want, now leave before I call the guard!" the man hurries back inside.    ')
    time.sleep(2)
    inventory.pop('MONEY FORM')
    inventory.append('MONEY FORM SIGNED')
    print('The MONEY FORM has been replaced with MONEY FORM SIGNED')
    time.sleep(2)
    print(f'Your current inventory: {inventory}')
    time.sleep(2)
    print('              Now that you have the MONEY FORM SIGNED, you decide to return to Ramsay.           ')
    time.sleep(4)
  if choice == 'threaten' and grit < 1:
    print("     You tell the man that you'll crash his party if he doesn't sign the form immediately.       ")
    time.sleep(2)
    print('                "Go ahead, just make sure to bring some soup." the man jests.                    ')
    time.sleep(2)
    print("                You don't seem to have enough GRIT to threaten the man properly.                 ")
    time.sleep(2)
    print('                     The man stops and appears to think for a moment.                            ')
    time.sleep(2)
    print('                           "You know what kid, tell you what."                                   ') 
    print('  "My back hurts. I havent made my payment for this door yet because I need medicine first."     ')
    time.sleep(2)
    print('        "If you can help me with that, I would be more than happy to sign that form."            ')
    time.sleep(2)
    print('You think for a moment and then remember that the nurse gave you a vial of SLIME ESCENSE earlier.')
    time.sleep(2)
    print("                 You're reluctant, but you feel like this may be the only way.                   ")
    time.sleep(2)
    print("          You tell the man that you will give him some medicine after he signs the form.         ")
    time.sleep(2)
    print('         "Before?! Why the hell would I agree to do that? Do you take me for a fool?"            ')
    time.sleep(2)
    print('     You glare at the man and tell him that you will break his legs too if he doesnt comply.     ')
    time.sleep(2)
    print('                                  "O-okay you thug! Here!"                                       ')
    time.sleep(2)
    inventory.pop('MONEY FORM')
    inventory.append('MONEY FORM SIGNED')
    print('The MONEY FORM has been replaced with MONEY FORM SIGNED')
    time.sleep(2)
    print(f'Your current inventory: {inventory}')
    time.sleep(4)
    print('   You throw some of the SLIME ESCENSE onto the mans hand and tell him to figure it out himself. ')
    time.sleep(2)
    print('                  He applies the SLIME ESCENSE and instantly stands upright.                     ')
    time.sleep(2)
    print('       "Thank you!... Now get the hell out of here!" The man slams the door in your face.        ')
    time.sleep(2)
  print('              Now that you have the MONEY FORM SIGNED, you decide to return to Ramsay.           ')
  time.sleep(2)
  print('       You return to Ramsay with the MONEY FORM SIGNED. He greets you with a bowl of soup.        ')
  print('                        "Well, looks like you shook em down!" he laughs.                          ')
  time.sleep(2)
  print('                               Ramsay claps his hands three times.                                ')
  print('                            Immediately, the carriage comes next to you.                          ')
  time.sleep(2)
  print('                 "Ill see ya off. Those roads can be awful dangerous sometimes."                  ')
  print('                   You and Ramsay both enter the carriage and it begins to go.                    ')
print('                            A couple of hours pass as you travel down the path.                       ')
time.sleep(2)
print("                           Before you know it, you've reached the Northern Wall!                      ")
time.sleep(2)